// player-statistics-angular/src/app/player-list/player-list.component.ts
import {Component, OnInit} from '@angular/core';
import {ActivatedRoute, Router} from "@angular/router";
import 'rxjs/add/operator/map';
import {Player} from "../../generated";
import {Observable} from "rxjs/Observable";

@Component({
  selector: 'app-player-list',
  templateUrl: './player-list.component.html',
  styleUrls: ['./player-list.component.scss']
})
export class PlayerListComponent implements OnInit {
  playerList: Observable<Player[]>;

  constructor(private activeRoute: ActivatedRoute,
              private router: Router) { }

  ngOnInit() {
    this.playerList = this.activeRoute.data.map((data) => data.playerList);
  }

  public navigateTo(playerId:number){
    this.router.navigate([`/player/${playerId}`])
  }

}

<table class="table table-striped table-bordered">
  <thead>
  <tr>
    <th>Ranking</th>
    <th>Name</th>
    <th>Tournament</th>
    <th>Details</th>
  </tr>
  </thead>
  <tbody class="playerList">
  <tr *ngFor="let player of playerList | async">
    <td>{{player.ranking}}</td>
    <td>{{player.firstName}} {{player.lastName}}</td>
    <td>{{player.tournamentName}}</td>
    <td class="text-center">
      <a class="details-link" (click)="navigateTo(player.playerId)"><i class="fa fa-long-arrow-right fa-2x"></i>
      </a></td>
  </tr>
  </tbody>
</table>

// player-statistics-react/src/Player-list.js
import React from 'react';
import {Link} from "react-router-dom";
import 'font-awesome/css/font-awesome.min.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'mdbreact/dist/css/mdb.css';

export default class PlayerList extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            playerList:[],
        }
    }

    componentWillMount(){
        fetch("/api/players")
            .then(res => res.json())
            .then(
                (result) => {
                    this.setState({
                        playerList: result
                    });
                },
                (error) => {
                    this.setState({
                        error
                    });
                }
            )
    }

    render() {

        return (
            <div>
                <table className="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th>Ranking</th>
                        <th>Name</th>
                        <th>Tournament</th>
                        <th>Details</th>
                    </tr>
                    </thead>
                    <tbody className="playerList">
                    {this.state.playerList.map(player => (
                        <tr key={player.playerId}>
                            <td>{player.ranking}</td>
                            <td>{player.firstName} {player.lastName}</td>
                            <td>{player.tournamentName}</td>
                            <td className="text-center">
                                <Link
                                    to={"/player/" + player.playerId}>
                                    <i className="fa fa-long-arrow-right fa-2x"></i></Link>
                            </td>
                        </tr>
                    ))}
                    </tbody>
                </table>
            </div>
        );
    }
}
